graph TD
  Header --> Nav
  Header --> useResize
  Header --> NavigationContext
  Header --> ScrollContext
  Header --> fnScrollUtils
  Nav --> NavLinkShow
  Nav --> NavInput
  Nav --> NavigationContext
  NavLinkShow --> RenderLink
  NavLinkShow --> SubMenu
  NavLinkShow --> NavigationContext
  RenderLink --> NavigationContext
  SubMenu --> NavigationContext
  updateMenuUtils --> NavigationContext
  scrollUtils --> ScrollContext
  scrollUtils --> fnScrollUtils
EOF
